Create "bonk" command
ssps-cajthaml/discord-bot pull request #25
Opened 2022-10-01 20:36 UTC by M4TY

2022-10-01 20:36 UTC, M4TY commented
https://github.com/ssps-cajthaml/discord-bot/issues/14

2022-10-01 21:31 UTC, cajthamlmatej requested changes

2022-10-01 21:31 UTC, cajthamlmatej commented on src/command/commands/bonk.ts
> +                // @ts-ignore
Why?

2022-10-01 21:31 UTC, cajthamlmatej commented on src/command/commands/bonk.ts
> +        collector.on('collect', (reaction: any, user: any) => {
any? we have these typed :(

2022-10-02 09:17 UTC, M4TY commented on src/command/commands/bonk.ts
> +                // @ts-ignore
Resolved with latest commit.

2022-10-02 09:17 UTC, M4TY commented on src/command/commands/bonk.ts
> +        collector.on('collect', (reaction: any, user: any) => {
Resolved with latest commit.

2022-10-02 09:44 UTC, cajthamlmatej approved these changes

2022-10-02 09:45 UTC, merged